version: '3.8'

services:
  metabase:
    image: metabase/metabase:latest
    container_name: tfm_metabase
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - metabase_data:/metabase.db
    depends_on:
      - mongo
    networks:
      - backend

  mongo:
    image: mongo:latest
    container_name: tfm_mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: jalope
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: tfm_db
    ports:
      - "27250:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: tfm_zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - backend

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: tfm_kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: tfm_zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://tfm_kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - backend

  kafka_connect:
    image: confluentinc/cp-kafka-connect:7.5.0
    container_name: tfm_kafka_connect
    restart: unless-stopped
    depends_on:
      - kafka
    ports:
      - "8083:8083"
    environment:
      # conexión a Kafka
      CONNECT_BOOTSTRAP_SERVERS: tfm_kafka:9092

      # REST API de Connect
      CONNECT_REST_PORT: 8083
      CONNECT_REST_ADVERTISED_HOST_NAME: "localhost"
      CONNECT_REST_ADVERTISED_PORT: "8083"

      # Forzar réplica=1 en los topics internos
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1

      # almacenamiento interno de configuraciones y offsets
      CONNECT_GROUP_ID: "kafka-connect-group"
      CONNECT_CONFIG_STORAGE_TOPIC: "connect-configs"
      CONNECT_OFFSET_STORAGE_TOPIC: "connect-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "connect-status"

      # serializadores de clave y valor
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.storage.StringConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"

      # ruta donde buscar plugins (dejamos solo los built-in)
      CONNECT_PLUGIN_PATH: "/usr/share/java"
    volumes:
      - ./shared:/data
    networks:
      - backend



volumes:
  metabase_data:
  mongo_data:

networks:
  backend:
    driver: bridge