version: '3.8'

services:
  metabase:
    image: metabase/metabase:latest
    container_name: tfm_metabase
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - tfm-bienvenida_metabase_data:/metabase.db
    depends_on:
      - mongo
    networks:
      - backend

  mongo:
    image: mongo:latest
    container_name: tfm_mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: jalope
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: tfm_db
    ports:
      - "27250:27017"
    volumes:
      - tfm-bienvenida_mongo_data:/data/db
    networks:
      - backend

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: tfm_zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - backend

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: tfm_kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: tfm_zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://tfm_kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - backend

  kafka_connect:
    image: confluentinc/cp-kafka-connect:7.5.0
    container_name: tfm_kafka_connect
    restart: unless-stopped
    depends_on:
      - kafka
    ports:
      - "8083:8083"
    environment:
      # conexión a Kafka
      CONNECT_BOOTSTRAP_SERVERS: tfm_kafka:9092

      # REST API de Connect
      CONNECT_REST_PORT: 8083
      CONNECT_REST_ADVERTISED_HOST_NAME: "localhost"
      CONNECT_REST_ADVERTISED_PORT: "8083"

      # Forzar réplica=1 en los topics internos
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1

      # almacenamiento interno de configuraciones y offsets
      CONNECT_GROUP_ID: "kafka-connect-group"
      CONNECT_CONFIG_STORAGE_TOPIC: "connect-configs"
      CONNECT_OFFSET_STORAGE_TOPIC: "connect-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "connect-status"

      # serializadores de clave y valor
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.storage.StringConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"

      # ruta donde buscar plugins (dejamos solo los built-in)
      CONNECT_PLUGIN_PATH: "/usr/share/java"
    volumes:
      - ./shared:/data
    networks:
      - backend
    # Construcción común para los ETL
  etl_base:
    build:
      context: ./etl
    image: tfm_etl:latest
    networks:
      - backend

  # 1. Extractor de la tabla 4583 → Kafka
  extract_ine_4583:
    image: tfm_etl:latest
    container_name: tfm_extract_ine_4583
    depends_on:
      - kafka
    command: ["python", "INE/4583/extract_ine_4583.py"]
    restart: "no"                   # solo se ejecuta una vez al levantar
    networks:
      - backend

  # 2. Transformador de la tabla 4583 (Kafka raw → Kafka processed)
  transform_ine_4583:
    image: tfm_etl:latest
    container_name: tfm_transform_ine_4583
    depends_on:
      - kafka
    command: ["python", "INE/4583/transform_ine_4583.py"]
    restart: unless-stopped         # consumidor continuo
    networks:
      - backend

  # 3. Cargador de la tabla 4583 en MongoDB
  load_ine_4583:
    image: tfm_etl:latest
    environment:
      - MONGO_URI=mongodb://jalope:admin@mongo:27017/tfm_db?authSource=admin&directConnection=true
    container_name: tfm_load_ine_4583
    depends_on:
      - kafka
      - mongo
    command: ["python", "INE/4583/load_ine_4583.py"]
    restart: unless-stopped         # consumidor continuo
    networks:
      - backend
  
  extract_gov10a_exp:
    image: tfm_etl:latest
    container_name: tfm_extract_gov10a_exp
    depends_on:
      - kafka
    command: ["python", "EUROSTAT/gov10a_exp/extract_gov10a_exp.py"]
    restart: "no"
    networks:
      - backend

  transform_gov10a_exp:
    image: tfm_etl:latest
    container_name: tfm_transform_gov10a_exp
    depends_on:
      - kafka
    command: ["python", "EUROSTAT/gov10a_exp/transform_gov10a_exp.py"]
    restart: unless-stopped
    networks:
      - backend

  load_gov10a_exp:
    image: tfm_etl:latest
    environment:
      - MONGO_URI=mongodb://jalope:admin@mongo:27017/tfm_db?authSource=admin&directConnection=true
    container_name: tfm_load_gov10a_exp
    depends_on:
      - kafka
      - mongo
    command: ["python", "EUROSTAT/gov10a_exp/load_gov10a_exp.py"]
    restart: unless-stopped
    networks:
      - backend

volumes:
  tfm-bienvenida_metabase_data:
    external: true
  tfm-bienvenida_mongo_data:
    external: true

networks:
  backend:
    driver: bridge